//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.IT.DiPaSport.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.IT.DiPaSport.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Cart.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION REQUEST.
        /// </summary>
        public static string AddToQuote {
            get {
                return ResourceManager.GetString("AddToQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiPaSport.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added to cart successfully.
        /// </summary>
        public static string CartAddSuccess {
            get {
                return ResourceManager.GetString("CartAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to use this feature.
        /// </summary>
        public static string CartConfirmToPay {
            get {
                return ResourceManager.GetString("CartConfirmToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your coupon code and click on confirm..
        /// </summary>
        public static string CartCouponContent {
            get {
                return ResourceManager.GetString("CartCouponContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The discount is not valid.
        /// </summary>
        public static string CartCouponInvail {
            get {
                return ResourceManager.GetString("CartCouponInvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coupon has already been used.
        /// </summary>
        public static string CartCouponIsUsed {
            get {
                return ResourceManager.GetString("CartCouponIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a discount click here.
        /// </summary>
        public static string CartDiscount {
            get {
                return ResourceManager.GetString("CartDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your discount.
        /// </summary>
        public static string CartDiscountCodeEmpty {
            get {
                return ResourceManager.GetString("CartDiscountCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string CartDiscountConfirm {
            get {
                return ResourceManager.GetString("CartDiscountConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon code is expired.
        /// </summary>
        public static string CartDiscountExpired {
            get {
                return ResourceManager.GetString("CartDiscountExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Discount.
        /// </summary>
        public static string CartDiscountLabel {
            get {
                return ResourceManager.GetString("CartDiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty.
        /// </summary>
        public static string CartEmpty {
            get {
                return ResourceManager.GetString("CartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the order.
        /// </summary>
        public static string CartOrder {
            get {
                return ResourceManager.GetString("CartOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order has been successfully completed. You will receive an email with all the information relating to your order..
        /// </summary>
        public static string CartOrderCompleted {
            get {
                return ResourceManager.GetString("CartOrderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Confirmation.
        /// </summary>
        public static string CartOrderConfirm {
            get {
                return ResourceManager.GetString("CartOrderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order will be sent. The total amount to be paid is.
        /// </summary>
        public static string CartOrderConfirmContent {
            get {
                return ResourceManager.GetString("CartOrderConfirmContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order fail, please try again !.
        /// </summary>
        public static string CartOrderFail {
            get {
                return ResourceManager.GetString("CartOrderFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string CartOrderNumber {
            get {
                return ResourceManager.GetString("CartOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD OTHER PRODUCTS.
        /// </summary>
        public static string CartOrderOptionsAddAnother {
            get {
                return ResourceManager.GetString("CartOrderOptionsAddAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETE THE ORDER.
        /// </summary>
        public static string CartOrderOptionsComplete {
            get {
                return ResourceManager.GetString("CartOrderOptionsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order sent successfully.
        /// </summary>
        public static string CartOrderSuccess {
            get {
                return ResourceManager.GetString("CartOrderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is already in cart.
        /// </summary>
        public static string CartProductExisting {
            get {
                return ResourceManager.GetString("CartProductExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string CartQuantity {
            get {
                return ResourceManager.GetString("CartQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iva.
        /// </summary>
        public static string CartTax {
            get {
                return ResourceManager.GetString("CartTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Taxable.
        /// </summary>
        public static string CartTotalWithoutTax {
            get {
                return ResourceManager.GetString("CartTotalWithoutTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total with IVA.
        /// </summary>
        public static string CartTotalWithTax {
            get {
                return ResourceManager.GetString("CartTotalWithTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cart.
        /// </summary>
        public static string CartYourCart {
            get {
                return ResourceManager.GetString("CartYourCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dipacommerce.com/appageiphone/?___store=en.
        /// </summary>
        public static string CMSPagePhone {
            get {
                return ResourceManager.GetString("CMSPagePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dipacommerce.com/apppage/?___store=en.
        /// </summary>
        public static string CMSPageTablet {
            get {
                return ResourceManager.GetString("CMSPageTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the application?.
        /// </summary>
        public static string ConfirmExitApp {
            get {
                return ResourceManager.GetString("ConfirmExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this product from the cart?.
        /// </summary>
        public static string ConfirmRemoveCart {
            get {
                return ResourceManager.GetString("ConfirmRemoveCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via della Chiusa, 24.
        /// </summary>
        public static string ContactAddress1 {
            get {
                return ResourceManager.GetString("ContactAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29010 Roveleto di Cadeo (PC) - Italy.
        /// </summary>
        public static string ContactAddress2 {
            get {
                return ResourceManager.GetString("ContactAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di.Pa. Sport Srl.
        /// </summary>
        public static string ContactCompany {
            get {
                return ResourceManager.GetString("ContactCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: info@dipasport.com.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where We Are.
        /// </summary>
        public static string ContactMap {
            get {
                return ResourceManager.GetString("ContactMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Network.
        /// </summary>
        public static string ContactSocial {
            get {
                return ResourceManager.GetString("ContactSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel. +39.0523509862.
        /// </summary>
        public static string ContactTelephone {
            get {
                return ResourceManager.GetString("ContactTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGENT.
        /// </summary>
        public static string CustomerTypeAgent {
            get {
                return ResourceManager.GetString("CustomerTypeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GARAGE SHOP.
        /// </summary>
        public static string CustomerTypeGarageShop {
            get {
                return ResourceManager.GetString("CustomerTypeGarageShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF S.
        /// </summary>
        public static string CustomerTypeOFFS {
            get {
                return ResourceManager.GetString("CustomerTypeOFFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVATE.
        /// </summary>
        public static string CustomerTypePrivate {
            get {
                return ResourceManager.GetString("CustomerTypePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETAILER.
        /// </summary>
        public static string CustomerTypeRetailer {
            get {
                return ResourceManager.GetString("CustomerTypeRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHOLESALER.
        /// </summary>
        public static string CustomerTypeWholeSaler {
            get {
                return ResourceManager.GetString("CustomerTypeWholeSaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or Register to see your prices, order or request a quote.
        /// </summary>
        public static string DetailAlertLogin {
            get {
                return ResourceManager.GetString("DetailAlertLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVAILABILITY.
        /// </summary>
        public static string DetailAvaiability {
            get {
                return ResourceManager.GetString("DetailAvaiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPATIBILITÀ.
        /// </summary>
        public static string DetailCompatibility {
            get {
                return ResourceManager.GetString("DetailCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezzi concorrenti:.
        /// </summary>
        public static string DetailCompetitivePrice {
            get {
                return ResourceManager.GetString("DetailCompetitivePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you banned. To reactivate the catalog and be able to purchase please contact us..
        /// </summary>
        public static string DetailCustomerBanned {
            get {
                return ResourceManager.GetString("DetailCustomerBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to see all pictures.
        /// </summary>
        public static string DetailHintPhoto {
            get {
                return ResourceManager.GetString("DetailHintPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONDITION OF PART.
        /// </summary>
        public static string DetailPartCondition {
            get {
                return ResourceManager.GetString("DetailPartCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested price for distributor:.
        /// </summary>
        public static string DetailPriceDistributor {
            get {
                return ResourceManager.GetString("DetailPriceDistributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested price for garage shop:.
        /// </summary>
        public static string DetailPriceGarageShop {
            get {
                return ResourceManager.GetString("DetailPriceGarageShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested price for retailer:.
        /// </summary>
        public static string DetailPriceRetailer {
            get {
                return ResourceManager.GetString("DetailPriceRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices will be visible within 24/48 hours after its entry.
        /// </summary>
        public static string DetailPriceUnAvailable {
            get {
                return ResourceManager.GetString("DetailPriceUnAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN STOCK. FOR THIS PART WE NEED THE OLD CORE BACK WITHIN {0} DAYS..
        /// </summary>
        public static string DetailProductAvailable {
            get {
                return ResourceManager.GetString("DetailProductAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PART NOT AVAILABLE. WE REPAIR YOURS. {0} WORKING DAYS TURNAROUND. SHIPPING NOT INCLUDED..
        /// </summary>
        public static string DetailProductUnavailble {
            get {
                return ResourceManager.GetString("DetailProductUnavailble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezzo di acquisto:.
        /// </summary>
        public static string DetailPurchsePrice {
            get {
                return ResourceManager.GetString("DetailPurchsePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEATURES.
        /// </summary>
        public static string DetailQuickOverView {
            get {
                return ResourceManager.GetString("DetailQuickOverView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codici Riferimento NASCOSTI DIPA.
        /// </summary>
        public static string DetailRefsCode {
            get {
                return ResourceManager.GetString("DetailRefsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lowered to &amp;#8364;.
        /// </summary>
        public static string DetailSpecialPrice {
            get {
                return ResourceManager.GetString("DetailSpecialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION.
        /// </summary>
        public static string DetailSuiablerFor {
            get {
                return ResourceManager.GetString("DetailSuiablerFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogCancel {
            get {
                return ResourceManager.GetString("DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogOK {
            get {
                return ResourceManager.GetString("DialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        public static string Euro {
            get {
                return ResourceManager.GetString("Euro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Order by QR code.
        /// </summary>
        public static string HomeBarCode {
            get {
                return ResourceManager.GetString("HomeBarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to call the number +390523509862?.
        /// </summary>
        public static string HomeCallConfirm {
            get {
                return ResourceManager.GetString("HomeCallConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALL US.
        /// </summary>
        public static string HomeCallUs {
            get {
                return ResourceManager.GetString("HomeCallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Category.
        /// </summary>
        public static string HomeCategory {
            get {
                return ResourceManager.GetString("HomeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last News:.
        /// </summary>
        public static string HomeLastNews {
            get {
                return ResourceManager.GetString("HomeLastNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by OEM / Di.Pa. Code.
        /// </summary>
        public static string HomeSearchHint {
            get {
                return ResourceManager.GetString("HomeSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo of the piece you&apos;re looking for.
        /// </summary>
        public static string HomeTakePicture {
            get {
                return ResourceManager.GetString("HomeTakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.dipasport.com.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi disinstallare e reinstallare l&apos;applicazione per cambiare la lingua.
        /// </summary>
        public static string LanguageMsgIT {
            get {
                return ResourceManager.GetString("LanguageMsgIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You be must re-install the application to change language.
        /// </summary>
        public static string LanguageMsgUK {
            get {
                return ResourceManager.GetString("LanguageMsgUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli la lingua.
        /// </summary>
        public static string LanguageSelectIT {
            get {
                return ResourceManager.GetString("LanguageSelectIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select default language.
        /// </summary>
        public static string LanguageSelectUK {
            get {
                return ResourceManager.GetString("LanguageSelectUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more results.
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot login.
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access....
        /// </summary>
        public static string Logining {
            get {
                return ResourceManager.GetString("Logining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have lost the password?.
        /// </summary>
        public static string LoginLostPassword {
            get {
                return ResourceManager.GetString("LoginLostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your username.
        /// </summary>
        public static string LoginNameEmpty {
            get {
                return ResourceManager.GetString("LoginNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your password.
        /// </summary>
        public static string LoginPasswordEmpty {
            get {
                return ResourceManager.GetString("LoginPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string LoginPasswordHint {
            get {
                return ResourceManager.GetString("LoginPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        public static string LoginRegisterButton {
            get {
                return ResourceManager.GetString("LoginRegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loggato.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Di.Pa. Sport.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        public static string LoginUsernameHint {
            get {
                return ResourceManager.GetString("LoginUsernameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        public static string LogoutConfirm {
            get {
                return ResourceManager.GetString("LogoutConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutConfirmTitle {
            get {
                return ResourceManager.GetString("LogoutConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email to reset your password.
        /// </summary>
        public static string LostPasswordContent {
            get {
                return ResourceManager.GetString("LostPasswordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your email.
        /// </summary>
        public static string LostPasswordEmailEmpty {
            get {
                return ResourceManager.GetString("LostPasswordEmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent a link to reset your password to your email.
        /// </summary>
        public static string LostPasswordMsg {
            get {
                return ResourceManager.GetString("LostPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during reset your password.
        /// </summary>
        public static string LostPasswordMsgFail {
            get {
                return ResourceManager.GetString("LostPasswordMsgFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string LostPasswordTitle {
            get {
                return ResourceManager.GetString("LostPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MenuAccount {
            get {
                return ResourceManager.GetString("MenuAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string MenuCart {
            get {
                return ResourceManager.GetString("MenuCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MenuSearch {
            get {
                return ResourceManager.GetString("MenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention, no internet connection..
        /// </summary>
        public static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        public static string OpenDetails {
            get {
                return ResourceManager.GetString("OpenDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +390523509862.
        /// </summary>
        public static string PhoneNumberContact {
            get {
                return ResourceManager.GetString("PhoneNumberContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM Code:.
        /// </summary>
        public static string ProductCodeOEM {
            get {
                return ResourceManager.GetString("ProductCodeOEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your price:.
        /// </summary>
        public static string ProductPricePrefix {
            get {
                return ResourceManager.GetString("ProductPricePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for 1 piece.
        /// </summary>
        public static string ProductPriceSuffix {
            get {
                return ResourceManager.GetString("ProductPriceSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowPhone APP.
        /// </summary>
        public static string RegisterByClient {
            get {
                return ResourceManager.GetString("RegisterByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City*.
        /// </summary>
        public static string RegisterCity {
            get {
                return ResourceManager.GetString("RegisterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name / Your Name if private*.
        /// </summary>
        public static string RegisterCompany {
            get {
                return ResourceManager.GetString("RegisterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country*.
        /// </summary>
        public static string RegisterCountry {
            get {
                return ResourceManager.GetString("RegisterCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string RegisterCustomerInfo {
            get {
                return ResourceManager.GetString("RegisterCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email*.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterEmailHint {
            get {
                return ResourceManager.GetString("RegisterEmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error registering.
        /// </summary>
        public static string RegisterFail {
            get {
                return ResourceManager.GetString("RegisterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string RegisterFax {
            get {
                return ResourceManager.GetString("RegisterFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name*.
        /// </summary>
        public static string RegisterFirstName {
            get {
                return ResourceManager.GetString("RegisterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration information.
        /// </summary>
        public static string RegisterHeader {
            get {
                return ResourceManager.GetString("RegisterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname*.
        /// </summary>
        public static string RegisterLastName {
            get {
                return ResourceManager.GetString("RegisterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Information.
        /// </summary>
        public static string RegisterLoginInfo {
            get {
                return ResourceManager.GetString("RegisterLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for our newsletter.
        /// </summary>
        public static string RegisterNewletters {
            get {
                return ResourceManager.GetString("RegisterNewletters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password*.
        /// </summary>
        public static string RegisterPasswordConfirm {
            get {
                return ResourceManager.GetString("RegisterPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your password*.
        /// </summary>
        public static string RegisterPasswordEmpty {
            get {
                return ResourceManager.GetString("RegisterPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string RegisterPasswordHint {
            get {
                return ResourceManager.GetString("RegisterPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 6 characters without spaces..
        /// </summary>
        public static string RegisterPasswordMinLength {
            get {
                return ResourceManager.GetString("RegisterPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure that the passwords match.
        /// </summary>
        public static string RegisterPasswordNotMatch {
            get {
                return ResourceManager.GetString("RegisterPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy *.
        /// </summary>
        public static string RegisterPrivacyLabel {
            get {
                return ResourceManager.GetString("RegisterPrivacyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information pursuant to Legislative Decree no. 196/03 on the protection of privacy (click to read).
        /// </summary>
        public static string RegisterPrivacyLink {
            get {
                return ResourceManager.GetString("RegisterPrivacyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept.
        /// </summary>
        public static string RegisterPrivacyOption {
            get {
                return ResourceManager.GetString("RegisterPrivacyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dipacommerce.com/privacy.
        /// </summary>
        public static string RegisterPrivacyUrl {
            get {
                return ResourceManager.GetString("RegisterPrivacyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Province.
        /// </summary>
        public static string RegisterStateProvince {
            get {
                return ResourceManager.GetString("RegisterStateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address *.
        /// </summary>
        public static string RegisterStreetAddress {
            get {
                return ResourceManager.GetString("RegisterStreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT or Tax Code.
        /// </summary>
        public static string RegisterTaxVat {
            get {
                return ResourceManager.GetString("RegisterTaxVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone*.
        /// </summary>
        public static string RegisterTelephone {
            get {
                return ResourceManager.GetString("RegisterTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Company*.
        /// </summary>
        public static string RegisterTypeOfCompany {
            get {
                return ResourceManager.GetString("RegisterTypeOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP*.
        /// </summary>
        public static string RegisterZipPostalCode {
            get {
                return ResourceManager.GetString("RegisterZipPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request product by App.
        /// </summary>
        public static string RequestEmailSubject {
            get {
                return ResourceManager.GetString("RequestEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all required fields.
        /// </summary>
        public static string RequestInputRequire {
            get {
                return ResourceManager.GetString("RequestInputRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates which parts you mean*.
        /// </summary>
        public static string RequestProductField1 {
            get {
                return ResourceManager.GetString("RequestProductField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate make, model and year of vehicle*.
        /// </summary>
        public static string RequestProductField2 {
            get {
                return ResourceManager.GetString("RequestProductField2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the brand and spare part.
        /// </summary>
        public static string RequestProductField3 {
            get {
                return ResourceManager.GetString("RequestProductField3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate the defect of the vehicle on the road.
        /// </summary>
        public static string RequestProductField4 {
            get {
                return ResourceManager.GetString("RequestProductField4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code and defect diagnosis with good description of the defect.
        /// </summary>
        public static string RequestProductField5 {
            get {
                return ResourceManager.GetString("RequestProductField5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &amp; Surname*.
        /// </summary>
        public static string RequestProductField6 {
            get {
                return ResourceManager.GetString("RequestProductField6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email*.
        /// </summary>
        public static string RequestProductField7 {
            get {
                return ResourceManager.GetString("RequestProductField7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone*.
        /// </summary>
        public static string RequestProductField8 {
            get {
                return ResourceManager.GetString("RequestProductField8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has been sent successfully to.
        /// </summary>
        public static string RequestSentMailSuccess {
            get {
                return ResourceManager.GetString("RequestSentMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string RequestUpload {
            get {
                return ResourceManager.GetString("RequestUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the search method.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT DETAILS.
        /// </summary>
        public static string SearchContactDetail {
            get {
                return ResourceManager.GetString("SearchContactDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code you want to search.
        /// </summary>
        public static string SearchKeywordEmpty {
            get {
                return ResourceManager.GetString("SearchKeywordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string SearchNotFound {
            get {
                return ResourceManager.GetString("SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the defect diagnosis code and description of the defect (for example: &quot;P-1000 oxygen sensor bank 1&quot;).
        /// </summary>
        public static string SearchRequesetFaultCodeDescription {
            get {
                return ResourceManager.GetString("SearchRequesetFaultCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string SearchRequestAddInfo {
            get {
                return ResourceManager.GetString("SearchRequestAddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate the brand of part*.
        /// </summary>
        public static string SearchRequestBrandOfPart {
            get {
                return ResourceManager.GetString("SearchRequestBrandOfPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company *.
        /// </summary>
        public static string SearchRequestCompany {
            get {
                return ResourceManager.GetString("SearchRequestCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the defect of the vehicle on the road*.
        /// </summary>
        public static string SearchRequestFaultOfVehicle {
            get {
                return ResourceManager.GetString("SearchRequestFaultOfVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION REQUEST.
        /// </summary>
        public static string SearchRequestInfo {
            get {
                return ResourceManager.GetString("SearchRequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the model*.
        /// </summary>
        public static string SearchRequestModelOfVehicle {
            get {
                return ResourceManager.GetString("SearchRequestModelOfVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for submitting your request.\nWe respond to you as quickly as possible.\nThe Di.Pa. Sport Team.
        /// </summary>
        public static string SearchRequestMsg {
            get {
                return ResourceManager.GetString("SearchRequestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search returned no results. Fill out the form below and you will be contacted soon by our staff..
        /// </summary>
        public static string SearchRequestMsgNotFound {
            get {
                return ResourceManager.GetString("SearchRequestMsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates which parts you mean *.
        /// </summary>
        public static string SearchRequestPart {
            get {
                return ResourceManager.GetString("SearchRequestPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate / codes that you find in the part*.
        /// </summary>
        public static string SearchRequestPartNumber {
            get {
                return ResourceManager.GetString("SearchRequestPartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your vehicle*.
        /// </summary>
        public static string SearchRequestTypeOfVehicle {
            get {
                return ResourceManager.GetString("SearchRequestTypeOfVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the picture of the parts if you have one.
        /// </summary>
        public static string SearchRequestUploadPictures {
            get {
                return ResourceManager.GetString("SearchRequestUploadPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results:.
        /// </summary>
        public static string SearchResultsLabel {
            get {
                return ResourceManager.GetString("SearchResultsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select default language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server impossible.
        /// </summary>
        public static string ServerNotResponse {
            get {
                return ResourceManager.GetString("ServerNotResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string StatusLoading {
            get {
                return ResourceManager.GetString("StatusLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m Searching....
        /// </summary>
        public static string StatusSearching {
            get {
                return ResourceManager.GetString("StatusSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an other photo.
        /// </summary>
        public static string TakePictureOptionsA {
            get {
                return ResourceManager.GetString("TakePictureOptionsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string TakePictureOptionsB {
            get {
                return ResourceManager.GetString("TakePictureOptionsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
